// <auto-generated />
namespace Deltax.Entity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class MovieTableAddedwithrelationtousertableasproducer : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MovieTableAddedwithrelationtousertableasproducer));
        
        string IMigrationMetadata.Id
        {
            get { return "201808300819326_MovieTable Added with relation to user table as producer"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
