// <auto-generated />
namespace Deltax.Entity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class bytearraysettonullinposter : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(bytearraysettonullinposter));
        
        string IMigrationMetadata.Id
        {
            get { return "201808221052097_byte array set to null in poster "; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
